package gui;

import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Admin
 */
public class ChuyenVienFrame extends javax.swing.JFrame {

    /**
     * Creates new form ChuyenVienFrame1
     */
    public ChuyenVienFrame() {
        initComponents();
        
        loadEmployeeDataFromFile();
    }
    private void loadEmployeeData() {
        // Fetch data from a source (e.g., database or API)
         
//        String hoTen = "Nguyen Van A";
//        String gioiTinh = "Nam";
//        String ngaySinh = "01/01/1990";
//        String sdt = "0123456789";
//        String email = "nguyenvana@example.com";
////        String luongCB = "15,000,000";
////        String phuCap = "2,000,000";
//        String ngayBatDau = "01/03/2015";
//        String ChucVu = "oc cho";
//        
//        NhanVien a = new NhanVien(hoTen, ChucVu, gioiTinh, email, sdt, ngaySinh, ngayBatDau);
//        // Populate fields
//        maNVField.setText(a.maNV);
//        hoTenField.setText(hoTen);
//        gioiTinhField.setText(gioiTinh);
//        
//        sdtField.setText(sdt);
//        emailField.setText(email);
////        luongCBField.setText(luongCB);
////        phuCapField.setText(phuCap);
//        ngayBatDauField.setText(ngayBatDau);
//        chucvu.setText(ChucVu);
          
    }
    
    private void loadEmployeeDataFromFile() {
        String filePath = "F:\\btaplon oop ver 2\\gui_btl-main\\BTL_OOP_GUI\\src\\gui\\x.txt"; // Path to your file
        try (BufferedReader br = new BufferedReader(new FileReader(filePath))) {
            String line = br.readLine(); // Read the first line
            if (line != null) {
                String[] data = line.split(","); // Split the line by comma
                if (data.length == 7) { // Ensure all fields are present
                    // Populate the fields
                    
                    NhanVien a = new NhanVien(data[0], data[1], data[2], data[3], data[4], data[5], data[6]);
                    
                    maNVField.setText(a.getMaNV());
                    hoTenField.setText(a.getTenNV());
                    gioiTinhField.setText(a.getGioiTinh());
                    ngaySinhField1.setText(a.getNgaySinh());
                    sdtField.setText(a.getSoDT());
                    emailField.setText(a.getEmail());
                    //luongCBField.setText(data[6]);
//                    phuCapField.setText(data[7]);
                    ngayBatDauField.setText(a.getNgayBatDau());
                    ngaySinhField.setText(a.getChucVu());
                } else {
                    JOptionPane.showMessageDialog(this, "Invalid data format in file.");
                }
            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error reading file: " + e.getMessage());
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chuyenVienFramePanel = new javax.swing.JPanel();
        headerPanel = new javax.swing.JPanel();
        emsTxt = new javax.swing.JLabel();
        clc02Txt = new javax.swing.JLabel();
        categoryPanel = new javax.swing.JPanel();
        logoutBtn = new javax.swing.JLabel();
        duAnBtn = new javax.swing.JPanel();
        duAnTxt = new javax.swing.JLabel();
        duAnSidePanel = new javax.swing.JPanel();
        ttcnBtn = new javax.swing.JPanel();
        ttcnTxt = new javax.swing.JLabel();
        ttcnSidePanel = new javax.swing.JPanel();
        nhanVienBtn = new javax.swing.JPanel();
        nhanVienTxt = new javax.swing.JLabel();
        nhanVienSidePanel = new javax.swing.JPanel();
        tabPanel = new javax.swing.JTabbedPane();
        panelNhanVien = new javax.swing.JPanel();
        nhanVienScrollTable = new javax.swing.JScrollPane();
        nhanVienTable = new javax.swing.JTable();
        nhanVienSearchBar = new javax.swing.JTextField();
        nhanVienSearchBtn = new javax.swing.JButton();
        panelDuAn = new javax.swing.JPanel();
        duAn1Tab = new javax.swing.JPanel();
        duAn2Tab = new javax.swing.JPanel();
        duAn3Tab = new javax.swing.JPanel();
        duAn4Tab = new javax.swing.JPanel();
        panelTTCN = new javax.swing.JPanel();
        maNVLabel = new javax.swing.JLabel();
        maNVField = new javax.swing.JLabel();
        hoTenLabel = new javax.swing.JLabel();
        hoTenField = new javax.swing.JLabel();
        gioiTinhLabel = new javax.swing.JLabel();
        gioiTinhField = new javax.swing.JLabel();
        ngaySinhLabel = new javax.swing.JLabel();
        ngaySinhField = new javax.swing.JLabel();
        sdtLabel = new javax.swing.JLabel();
        sdtField = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        emailField = new javax.swing.JLabel();
        luongCBLabel = new javax.swing.JLabel();
        luongCBField = new javax.swing.JLabel();
        ngayBDLabel = new javax.swing.JLabel();
        ngayBatDauField = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nameviettat = new javax.swing.JTextField();
        ngaySinhField1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("EMS");
        setLocationByPlatform(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        chuyenVienFramePanel.setBackground(new java.awt.Color(205, 225, 238));
        chuyenVienFramePanel.setMaximumSize(new java.awt.Dimension(230, 632));
        chuyenVienFramePanel.setMinimumSize(new java.awt.Dimension(230, 632));
        chuyenVienFramePanel.setPreferredSize(new java.awt.Dimension(230, 632));
        chuyenVienFramePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        headerPanel.setBackground(new java.awt.Color(74, 98, 138));
        headerPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        headerPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        emsTxt.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        emsTxt.setForeground(new java.awt.Color(255, 255, 255));
        emsTxt.setText("EMS");
        headerPanel.add(emsTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        clc02Txt.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        clc02Txt.setForeground(new java.awt.Color(205, 225, 238));
        clc02Txt.setText("CLC-02");
        headerPanel.add(clc02Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        chuyenVienFramePanel.add(headerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 50));

        categoryPanel.setBackground(new java.awt.Color(144, 176, 194));
        categoryPanel.setMinimumSize(new java.awt.Dimension(240, 240));
        categoryPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logoutBtn.setBackground(new java.awt.Color(0, 0, 0));
        logoutBtn.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        logoutBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Logout.png"))); // NOI18N
        logoutBtn.setText("LOGOUT");
        logoutBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutBtnMouseEntered(evt);
            }
        });
        categoryPanel.add(logoutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 600, -1, -1));

        duAnBtn.setBackground(new java.awt.Color(205, 225, 238));
        duAnBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                duAnBtnMouseClicked(evt);
            }
        });
        duAnBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        duAnTxt.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        duAnTxt.setForeground(new java.awt.Color(74, 98, 138));
        duAnTxt.setText("Thông tin Cá nhân");
        duAnBtn.add(duAnTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 150, 50));

        duAnSidePanel.setBackground(new java.awt.Color(74, 98, 138));
        duAnBtn.add(duAnSidePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 50));

        categoryPanel.add(duAnBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 240, 50));

        ttcnBtn.setBackground(new java.awt.Color(205, 225, 238));
        ttcnBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ttcnBtnMouseClicked(evt);
            }
        });
        ttcnBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ttcnTxt.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        ttcnTxt.setForeground(new java.awt.Color(74, 98, 138));
        ttcnTxt.setText("Dự Án");
        ttcnBtn.add(ttcnTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 110, 50));

        ttcnSidePanel.setBackground(new java.awt.Color(74, 98, 138));
        ttcnBtn.add(ttcnSidePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 50));

        categoryPanel.add(ttcnBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 240, 50));

        nhanVienBtn.setBackground(new java.awt.Color(74, 98, 138));
        nhanVienBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nhanVienBtnMouseClicked(evt);
            }
        });
        nhanVienBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nhanVienTxt.setBackground(new java.awt.Color(205, 225, 238));
        nhanVienTxt.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        nhanVienTxt.setForeground(new java.awt.Color(255, 255, 255));
        nhanVienTxt.setText("Nhân Viên");
        nhanVienBtn.add(nhanVienTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 5, 150, 40));

        nhanVienSidePanel.setBackground(new java.awt.Color(255, 255, 255));
        nhanVienBtn.add(nhanVienSidePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 50));

        categoryPanel.add(nhanVienBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 240, 50));

        chuyenVienFramePanel.add(categoryPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 240, 700));

        panelNhanVien.setBackground(new java.awt.Color(228, 238, 244));
        panelNhanVien.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nhanVienTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        nhanVienScrollTable.setViewportView(nhanVienTable);

        panelNhanVien.add(nhanVienScrollTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 900, 470));

        nhanVienSearchBar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nhanVienSearchBarActionPerformed(evt);
            }
        });
        panelNhanVien.add(nhanVienSearchBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 90, 240, -1));

        nhanVienSearchBtn.setText("jButton4");
        panelNhanVien.add(nhanVienSearchBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 90, -1, -1));

        tabPanel.addTab("tab1", panelNhanVien);

        panelDuAn.setBackground(new java.awt.Color(228, 238, 244));
        panelDuAn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        duAn1Tab.setBackground(new java.awt.Color(255, 255, 255));
        duAn1Tab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                duAn1TabMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                duAn1TabMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                duAn1TabMouseExited(evt);
            }
        });
        panelDuAn.add(duAn1Tab, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, 170, 110));

        duAn2Tab.setBackground(new java.awt.Color(255, 255, 255));
        duAn2Tab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                duAn2TabMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                duAn2TabMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                duAn2TabMouseExited(evt);
            }
        });
        panelDuAn.add(duAn2Tab, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 150, 170, 110));

        duAn3Tab.setBackground(new java.awt.Color(255, 255, 255));
        duAn3Tab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                duAn3TabMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                duAn3TabMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                duAn3TabMouseExited(evt);
            }
        });
        panelDuAn.add(duAn3Tab, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 170, 110));

        duAn4Tab.setBackground(new java.awt.Color(255, 255, 255));
        duAn4Tab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                duAn4TabMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                duAn4TabMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                duAn4TabMouseExited(evt);
            }
        });
        duAn4Tab.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelDuAn.add(duAn4Tab, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 170, 110));

        tabPanel.addTab("tab3", panelDuAn);

        panelTTCN.setBackground(new java.awt.Color(228, 238, 244));
        panelTTCN.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        maNVLabel.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        maNVLabel.setForeground(new java.awt.Color(51, 51, 255));
        maNVLabel.setText("Mã Nhân Viên:");
        panelTTCN.add(maNVLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, -1, 40));

        maNVField.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        maNVField.setForeground(new java.awt.Color(51, 51, 255));
        maNVField.setText("null");
        panelTTCN.add(maNVField, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, -1, 40));

        hoTenLabel.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        hoTenLabel.setForeground(new java.awt.Color(51, 51, 255));
        hoTenLabel.setText("Họ và Tên:");
        panelTTCN.add(hoTenLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, -1, 40));

        hoTenField.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        hoTenField.setForeground(new java.awt.Color(51, 51, 255));
        hoTenField.setText("null");
        panelTTCN.add(hoTenField, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, -1, 40));

        gioiTinhLabel.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        gioiTinhLabel.setForeground(new java.awt.Color(51, 51, 255));
        gioiTinhLabel.setText("Giới tính:");
        panelTTCN.add(gioiTinhLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, -1, 40));

        gioiTinhField.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        gioiTinhField.setForeground(new java.awt.Color(51, 51, 255));
        gioiTinhField.setText("null");
        panelTTCN.add(gioiTinhField, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, -1, 40));

        ngaySinhLabel.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        ngaySinhLabel.setForeground(new java.awt.Color(51, 51, 255));
        ngaySinhLabel.setText("Ngày sinh:");
        panelTTCN.add(ngaySinhLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 300, -1, 40));

        ngaySinhField.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        ngaySinhField.setText("chucvu");
        panelTTCN.add(ngaySinhField, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, -1, 40));

        sdtLabel.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        sdtLabel.setForeground(new java.awt.Color(51, 51, 255));
        sdtLabel.setText("Số điện thoại:");
        panelTTCN.add(sdtLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 300, -1, 40));

        sdtField.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        sdtField.setForeground(new java.awt.Color(51, 51, 255));
        sdtField.setText("null");
        panelTTCN.add(sdtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 340, -1, 40));

        emailLabel.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        emailLabel.setForeground(new java.awt.Color(51, 51, 255));
        emailLabel.setText("Email:");
        panelTTCN.add(emailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 220, -1, 40));

        emailField.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        emailField.setForeground(new java.awt.Color(51, 51, 255));
        emailField.setText("null");
        panelTTCN.add(emailField, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 270, -1, 40));

        luongCBLabel.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        luongCBLabel.setForeground(new java.awt.Color(51, 51, 255));
        luongCBLabel.setText("Lương cơ bản:");
        panelTTCN.add(luongCBLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 60, -1, 40));

        luongCBField.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        luongCBField.setForeground(new java.awt.Color(51, 51, 255));
        luongCBField.setText("null");
        panelTTCN.add(luongCBField, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 100, -1, 40));

        ngayBDLabel.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        ngayBDLabel.setForeground(new java.awt.Color(51, 51, 255));
        ngayBDLabel.setText("Ngày bắt đầu làm việc:");
        panelTTCN.add(ngayBDLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 140, -1, 40));

        ngayBatDauField.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        ngayBatDauField.setForeground(new java.awt.Color(51, 51, 255));
        ngayBatDauField.setText("null");
        panelTTCN.add(ngayBatDauField, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 180, -1, 40));

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("pornhub");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(429, 429, 429)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(439, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        panelTTCN.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 540, 960, 150));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Screenshot 2024-11-28 095235.png"))); // NOI18N
        jLabel2.setPreferredSize(new java.awt.Dimension(200, 200));
        panelTTCN.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 270, 220));

        nameviettat.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nameviettat.setText("jTextField2");
        nameviettat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameviettatActionPerformed(evt);
            }
        });
        panelTTCN.add(nameviettat, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 110, 40));

        ngaySinhField1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        ngaySinhField1.setForeground(new java.awt.Color(51, 51, 255));
        ngaySinhField1.setText("null");
        panelTTCN.add(ngaySinhField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 340, -1, 40));

        tabPanel.addTab("tab2", panelTTCN);

        chuyenVienFramePanel.add(tabPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, -40, 960, 730));

        getContentPane().add(chuyenVienFramePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 690));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void duAn4TabMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_duAn4TabMouseExited
        // TODO add your handling code here:
        duAn4Tab.setBackground( new Color(255, 255, 255));
    }//GEN-LAST:event_duAn4TabMouseExited

    private void duAn4TabMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_duAn4TabMouseEntered
        // TODO add your handling code here:
        duAn4Tab.setBackground( new Color(112, 132, 165));
    }//GEN-LAST:event_duAn4TabMouseEntered

    private void duAn4TabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_duAn4TabMouseClicked
        // TODO add your handling code here:

        new ChuyenVienFrameDuAn().setVisible(true);
    }//GEN-LAST:event_duAn4TabMouseClicked

    private void duAn3TabMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_duAn3TabMouseExited
        // TODO add your handling code here:
        duAn3Tab.setBackground( new Color(255, 255, 255));
    }//GEN-LAST:event_duAn3TabMouseExited

    private void duAn3TabMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_duAn3TabMouseEntered
        // TODO add your handling code here:
        duAn3Tab.setBackground( new Color(112, 132, 165));
    }//GEN-LAST:event_duAn3TabMouseEntered

    private void duAn3TabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_duAn3TabMouseClicked
        // TODO add your handling code here:
        new ChuyenVienFrameDuAn().setVisible(true);
    }//GEN-LAST:event_duAn3TabMouseClicked

    private void duAn2TabMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_duAn2TabMouseExited
        // TODO add your handling code here:
        duAn2Tab.setBackground( new Color(255, 255, 255));
    }//GEN-LAST:event_duAn2TabMouseExited

    private void duAn2TabMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_duAn2TabMouseEntered
        // TODO add your handling code here:
        duAn2Tab.setBackground( new Color(112, 132, 165));
    }//GEN-LAST:event_duAn2TabMouseEntered

    private void duAn2TabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_duAn2TabMouseClicked
        // TODO add your handling code here:
        new ChuyenVienFrameDuAn().setVisible(true);
    }//GEN-LAST:event_duAn2TabMouseClicked

    private void duAn1TabMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_duAn1TabMouseExited
        // TODO add your handling code here:
        duAn1Tab.setBackground( new Color(255, 255, 255));
    }//GEN-LAST:event_duAn1TabMouseExited

    private void duAn1TabMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_duAn1TabMouseEntered
        // TODO add your handling code here:
        duAn1Tab.setBackground( new Color(112, 132, 165));
    }//GEN-LAST:event_duAn1TabMouseEntered

    private void duAn1TabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_duAn1TabMouseClicked
        // TODO add your handling code here:
        new ChuyenVienFrameDuAn().setVisible(true);
    }//GEN-LAST:event_duAn1TabMouseClicked

    private void nhanVienSearchBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nhanVienSearchBarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nhanVienSearchBarActionPerformed

    private void logoutBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutBtnMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_logoutBtnMouseEntered

    private void logoutBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutBtnMouseClicked
        // TODO add your handling code here:
        int tmp = JOptionPane.showConfirmDialog(this,"Confirm Logout?", "Logout", JOptionPane.YES_NO_OPTION);
        if ( tmp == 0 ) {
            new Login().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_logoutBtnMouseClicked

    private void nhanVienBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nhanVienBtnMouseClicked
        nhanVienBtn.setBackground(new Color(74, 98, 138));
        nhanVienTxt.setForeground(new Color(255, 255, 255));
        nhanVienSidePanel.setBackground(new Color(255, 255, 255));
        
        ttcnBtn.setBackground(new Color(205,225,238));
        ttcnTxt.setForeground(new Color(74,98,138));
        ttcnSidePanel.setBackground(new Color(74,98,138));
        
        duAnBtn.setBackground(new Color(205,225,238));
        duAnTxt.setForeground(new Color(74,98,138));
        duAnSidePanel.setBackground(new Color(74,98,138));
        
        tabPanel.setSelectedIndex(0);        
    }//GEN-LAST:event_nhanVienBtnMouseClicked

    private void ttcnBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ttcnBtnMouseClicked
        ttcnBtn.setBackground(new Color(74, 98, 138));
        ttcnTxt.setForeground(new Color(255, 255, 255));
        ttcnSidePanel.setBackground(new Color(255, 255, 255));
        
        nhanVienBtn.setBackground(new Color(205,225,238));
        nhanVienTxt.setForeground(new Color(74,98,138));
        nhanVienSidePanel.setBackground(new Color(74,98,138));
        
        duAnBtn.setBackground(new Color(205,225,238));
        duAnTxt.setForeground(new Color(74,98,138));
        duAnSidePanel.setBackground(new Color(74,98,138));
        
        tabPanel.setSelectedIndex(1);
    }//GEN-LAST:event_ttcnBtnMouseClicked

    private void duAnBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_duAnBtnMouseClicked
        duAnBtn.setBackground(new Color(74, 98, 138));
        duAnTxt.setForeground(new Color(255, 255, 255));
        duAnSidePanel.setBackground(new Color(255, 255, 255));
        
        nhanVienBtn.setBackground(new Color(205,225,238));
        nhanVienTxt.setForeground(new Color(74,98,138));
        nhanVienSidePanel.setBackground(new Color(74,98,138));
        
        ttcnBtn.setBackground(new Color(205,225,238));
        ttcnTxt.setForeground(new Color(74,98,138));
        ttcnSidePanel.setBackground(new Color(74,98,138));
        tabPanel.setSelectedIndex(2);
    }//GEN-LAST:event_duAnBtnMouseClicked

    private void nameviettatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameviettatActionPerformed
            
        nameviettat.setText("haha");
    }//GEN-LAST:event_nameviettatActionPerformed
     
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChuyenVienFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChuyenVienFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChuyenVienFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChuyenVienFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChuyenVienFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel categoryPanel;
    private javax.swing.JPanel chuyenVienFramePanel;
    private javax.swing.JLabel clc02Txt;
    private javax.swing.JPanel duAn1Tab;
    private javax.swing.JPanel duAn2Tab;
    private javax.swing.JPanel duAn3Tab;
    private javax.swing.JPanel duAn4Tab;
    private javax.swing.JPanel duAnBtn;
    private javax.swing.JPanel duAnSidePanel;
    private javax.swing.JLabel duAnTxt;
    private javax.swing.JLabel emailField;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JLabel emsTxt;
    private javax.swing.JLabel gioiTinhField;
    private javax.swing.JLabel gioiTinhLabel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel hoTenField;
    private javax.swing.JLabel hoTenLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel logoutBtn;
    private javax.swing.JLabel luongCBField;
    private javax.swing.JLabel luongCBLabel;
    private javax.swing.JLabel maNVField;
    private javax.swing.JLabel maNVLabel;
    private javax.swing.JTextField nameviettat;
    private javax.swing.JLabel ngayBDLabel;
    private javax.swing.JLabel ngayBatDauField;
    private javax.swing.JLabel ngaySinhField;
    private javax.swing.JLabel ngaySinhField1;
    private javax.swing.JLabel ngaySinhLabel;
    private javax.swing.JPanel nhanVienBtn;
    private javax.swing.JScrollPane nhanVienScrollTable;
    private javax.swing.JTextField nhanVienSearchBar;
    private javax.swing.JButton nhanVienSearchBtn;
    private javax.swing.JPanel nhanVienSidePanel;
    private javax.swing.JTable nhanVienTable;
    private javax.swing.JLabel nhanVienTxt;
    private javax.swing.JPanel panelDuAn;
    private javax.swing.JPanel panelNhanVien;
    private javax.swing.JPanel panelTTCN;
    private javax.swing.JLabel sdtField;
    private javax.swing.JLabel sdtLabel;
    private javax.swing.JTabbedPane tabPanel;
    private javax.swing.JPanel ttcnBtn;
    private javax.swing.JPanel ttcnSidePanel;
    private javax.swing.JLabel ttcnTxt;
    // End of variables declaration//GEN-END:variables
}
